//! Fixed property orders for StructureDefinition / ElementDefinition JSON.
//! Verbatim from `sushi-ts/src/fhirtypes/StructureDefinition.ts:1053` and
//! `ElementDefinition.ts:3285`.

/// `StructureDefinition.PROPS` (`StructureDefinition.ts:1053`).
pub const SD_PROPS: &[&str] = &[
    "id",
    "meta",
    "implicitRules",
    "language",
    "text",
    "contained",
    "extension",
    "modifierExtension",
    "url",
    "identifier",
    "version",
    "name",
    "title",
    "status",
    "experimental",
    "date",
    "publisher",
    "contact",
    "description",
    "useContext",
    "jurisdiction",
    "purpose",
    "copyright",
    "keyword",
    "fhirVersion",
    "mapping",
    "kind",
    "abstract",
    "context",
    "contextInvariant",
    "type",
    "baseDefinition",
    "derivation",
];

/// `ElementDefinition.PROPS` (`ElementDefinition.ts:3285`).
pub const ED_PROPS: &[&str] = &[
    "id",
    "extension",
    "modifierExtension",
    "path",
    "representation",
    "sliceName",
    "sliceIsConstraining",
    "label",
    "code",
    "slicing",
    "short",
    "definition",
    "comment",
    "requirements",
    "alias",
    "min",
    "max",
    "base",
    "contentReference",
    "type",
    "defaultValue[x]",
    "meaningWhenMissing",
    "orderMeaning",
    "fixed[x]",
    "pattern[x]",
    "example",
    "minValue[x]",
    "maxValue[x]",
    "maxLength",
    "condition",
    "constraint",
    "mustSupport",
    "isModifier",
    "isModifierReason",
    "isSummary",
    "binding",
    "mapping",
];
