
Logical: KeywordLogical
* MS 0..1 string "Element named MS"
* SU 0..2 number "Element named SU"
* TU 1..1 boolean "Element named TU"
* N 0..* code "Element named N"
* D 1..* MS Coding "Element named D"
* from 0..1 Address "From an address"
* contains 0..* string "Contains many strings"
* named 1..1 HumanName "Has a name"
* and 0..1 boolean "And what?"
* only 0..1 number "Only number"
* or 0..3 string "Or three strings"
* obeys 1..1 boolean "Obey boolean"
* true 0..1 boolean "Please don't make an element named true"
* false 0..1 boolean "Please don't make an element named false, either"
* include 0..1 Coding "Include a coding"
* exclude 0..1 Coding "Exclude a coding"
* codes 0..* code "List of codes"
* where 1..1 Address "Where is it?"
* valueset 0..1 uri "Give me a value set"
* system 0..1 uri "Give me a system"
* contentReference 1..1 contentReference http://example.org/StructureDefinition/Keywords#Keywords.content "A content reference with a content reference"
