//! `menu.xml` generation from the sushi-config `menu:` tree — the Bootstrap
//! navbar SUSHI writes into `fsh-generated/includes/menu.xml`, which the IG
//! template layouts pull in with `{% include menu.xml %}`. The navbar is pure IG
//! data (each entry is authored in `sushi-config.yaml`), NOT template chrome, so
//! it must be generated per-IG — the template only supplies the include point.
//!
//! Model (SUSHI supports two levels): each top-level `menu:` entry is either a
//! LEAF (`Label: url` → a plain nav link) or a DROPDOWN (`Label:` with a nested
//! map of `Label: url` children → a Bootstrap dropdown). Order is preserved.

use serde_yaml::Value;

/// The header SUSHI stamps on the generated file (inside a Liquid comment, so it
/// never renders). Reproduced for fidelity with the publisher's `menu.xml`.
const HEADER: &str = "<!-- menu.xml {% comment %}\n\
*****************************************************************************************************\n\
*                                  WARNING: DO NOT EDIT THIS FILE                                   *\n\
*                                                                                                   *\n\
* This file is generated by SUSHI. Any edits you make to this file will be overwritten.             *\n\
*                                                                                                   *\n\
* To change the contents of this file, edit the \"menu\" attribute in the tank sushi-config.yaml file *\n\
* or provide your own menu.xml in the input/includes folder                                         *\n\
*****************************************************************************************************\n\
{% endcomment %} -->\n\n";

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Generate `menu.xml` from a sushi-config YAML string. Returns `None` when the
/// config has no `menu:` block (nothing to generate).
pub fn menu_xml(cfg_yaml: &str) -> Option<String> {
    let root: Value = serde_yaml::from_str(cfg_yaml).ok()?;
    let menu = root.get("menu")?.as_mapping()?;

    let mut out = String::from(HEADER);
    out.push_str("<ul xmlns=\"http://www.w3.org/1999/xhtml\" class=\"nav navbar-nav\">\n");
    for (label, value) in menu {
        let Some(label) = label.as_str() else {
            continue;
        };
        match value {
            // Dropdown: nested map of child links.
            Value::Mapping(children) => {
                out.push_str("  <li class=\"dropdown\">\n");
                out.push_str(&format!(
                    "    <a data-toggle=\"dropdown\" href=\"#\" class=\"dropdown-toggle\">{}\n      <b class=\"caret\"></b>\n    </a>\n",
                    esc(label)
                ));
                out.push_str("    <ul class=\"dropdown-menu\">\n");
                for (clabel, curl) in children {
                    let (Some(clabel), Some(curl)) = (clabel.as_str(), curl.as_str()) else {
                        continue;
                    };
                    out.push_str(&format!(
                        "      <li>\n        <a href=\"{}\">{}</a>\n      </li>\n",
                        esc(curl),
                        esc(clabel)
                    ));
                }
                out.push_str("    </ul>\n  </li>\n");
            }
            // Leaf: a plain top-level link.
            Value::String(url) => {
                out.push_str(&format!(
                    "  <li>\n    <a href=\"{}\">{}</a>\n  </li>\n",
                    esc(url),
                    esc(label)
                ));
            }
            _ => {}
        }
    }
    out.push_str("</ul>");
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn leaf_and_dropdown() {
        let cfg = "\
menu:\n  Home: index.html\n  Guidance:\n    Overview: guidance.html\n    Notes: notes.html\n";
        let xml = menu_xml(cfg).unwrap();
        assert!(xml.contains("<a href=\"index.html\">Home</a>"));
        assert!(xml.contains("class=\"dropdown-toggle\">Guidance"));
        assert!(xml.contains("<a href=\"guidance.html\">Overview</a>"));
        assert!(xml.contains("<ul class=\"dropdown-menu\">"));
    }

    #[test]
    fn no_menu_is_none() {
        assert!(menu_xml("canonical: http://example.org").is_none());
    }
}
