//! Port of `org.hl7.fhir.utilities.xhtml.XhtmlNode` / `NodeType` / `XhtmlDocument`.
//!
//! Source of truth (READ-ONLY):
//!   fhir-core/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/xhtml/XhtmlNode.java
//!   fhir-core/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/xhtml/NodeType.java
//!   fhir-core/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/xhtml/XhtmlDocument.java
//!
//! ## Deliberate divergence: attribute ordering
//!
//! Java's `XhtmlNode.attributes` is a plain `HashMap<String,String>`
//! (XhtmlNode.java:142), so the composer emits attributes in Java HashMap
//! iteration order (XhtmlComposer.java:308 `getAttributes().keySet()`).
//!
//! That order is NOT preserved by a parse->compose round-trip in Java itself:
//! the parser inserts attributes in source order, but the composer re-reads
//! them in HashMap-hash order. Verified against the golden corpus: e.g. the
//! `xml-html` fragment's `<pre class="xml" data-fhir="generated" style="...">`
//! is emitted by the publisher as a RAW STRING (XmlXHtmlRenderer.java:87, never
//! through the composer), so its attribute order is authorial. Feeding that
//! through Java parse->compose yields `<pre style="..." class="xml"
//! data-fhir="generated">` — different bytes.
//!
//! The C3 gate is explicitly "parse each golden fragment then compose ->
//! byte-identical". That gate is ONLY satisfiable with an insertion-ordered
//! attribute map: the parser records attributes in source order, the composer
//! emits them in that same order, so ANY well-formed fragment (composer-authored
//! OR raw-string) round-trips byte-exact. We therefore use an insertion-ordered
//! map. When WE later synthesize fragments (F2/F3 tables etc.) we will insert
//! attributes in the order Java's HashMap would have iterated them, so the
//! generated bytes match the goldens — but that is downstream work; for the C3
//! substrate, insertion-order preservation is the correct and necessary choice.

use crate::ordermap::OrderMap;

/// Port of `NodeType` (NodeType.java:34).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NodeType {
    Element,
    Text,
    Comment,
    DocType,
    Document,
    Instruction,
    CData,
}

/// U+00A0 non-breaking space. Java: `XhtmlNode.NBSP` (XhtmlNode.java:80).
pub const NBSP: char = '\u{00A0}';

/// Port of `XhtmlNode` (and `XhtmlDocument`, which is just a node with
/// `NodeType.Document`).
#[derive(Debug, Clone)]
pub struct XhtmlNode {
    node_type: NodeType,
    name: Option<String>,
    /// Insertion-ordered (see module docs). A value of `None` represents a
    /// value-less attribute (`<x foo>`), matching Java where the parser stores
    /// `null` (XhtmlParser.java:733).
    attributes: OrderMap<String, Option<String>>,
    child_nodes: Vec<XhtmlNode>,
    content: Option<String>,
    /// Java `notPretty` (XhtmlNode.java:92). Set for inline elements by
    /// `makeTag` (XhtmlNode.java:236). Only affects pretty output.
    not_pretty: bool,
    /// Java `emptyExpanded` (Boolean, tri-state via Option) (XhtmlNode.java:94).
    empty_expanded: Option<bool>,
}

impl XhtmlNode {
    pub fn new(node_type: NodeType) -> Self {
        XhtmlNode {
            node_type,
            name: None,
            attributes: OrderMap::new(),
            child_nodes: Vec::new(),
            content: None,
            not_pretty: false,
            empty_expanded: None,
        }
    }

    pub fn new_document() -> Self {
        XhtmlNode::new(NodeType::Document)
    }

    pub fn node_type(&self) -> NodeType {
        self.node_type
    }

    pub fn name(&self) -> Option<&str> {
        self.name.as_deref()
    }

    /// Java `setName` (XhtmlNode.java:127). Java asserts no ':' and toggles the
    /// paragraph-tree flag; neither affects serialization, so we only store.
    pub fn set_name(&mut self, name: impl Into<String>) -> &mut Self {
        self.name = Some(name.into());
        self
    }

    pub fn content(&self) -> Option<&str> {
        self.content.as_deref()
    }

    /// Java `setContent` (XhtmlNode.java:163).
    pub fn set_content(&mut self, content: impl Into<String>) -> &mut Self {
        self.content = Some(content.into());
        self
    }

    // --- attributes ---

    pub fn attributes(&self) -> &OrderMap<String, Option<String>> {
        &self.attributes
    }

    pub fn attributes_mut(&mut self) -> &mut OrderMap<String, Option<String>> {
        &mut self.attributes
    }

    /// Java `hasAttributes` (XhtmlNode.java:136).
    pub fn has_attributes(&self) -> bool {
        !self.attributes.is_empty()
    }

    pub fn set_attribute(
        &mut self,
        name: impl Into<String>,
        value: impl Into<String>,
    ) -> &mut Self {
        self.attributes.put(name.into(), Some(value.into()));
        self
    }

    /// Put an attribute with a `null` (value-less) value, as the parser does
    /// for `<x foo>` (XhtmlParser.java:733).
    pub fn put_attribute_null(&mut self, name: impl Into<String>) {
        self.attributes.put(name.into(), None);
    }

    pub fn put_attribute_opt(&mut self, name: impl Into<String>, value: Option<String>) {
        self.attributes.put(name.into(), value);
    }

    /// Java `getElement(name)` (XhtmlNode.java:363) — first child element with
    /// the given name. Used by the composer's `head`/`meta` special-case
    /// (XhtmlComposer.java:337).
    pub fn get_element(&self, name: &str) -> Option<&XhtmlNode> {
        self.child_nodes
            .iter()
            .find(|n| n.node_type == NodeType::Element && n.name.as_deref() == Some(name))
    }

    // --- children ---

    pub fn child_nodes(&self) -> &[XhtmlNode] {
        &self.child_nodes
    }

    pub fn child_nodes_mut(&mut self) -> &mut Vec<XhtmlNode> {
        &mut self.child_nodes
    }

    /// Java `hasChildren` (XhtmlNode.java:147).
    pub fn has_children(&self) -> bool {
        !self.child_nodes.is_empty()
    }

    /// Java `hasContent`. In XhtmlNode.java this is:
    /// `return content != null;` for text-like nodes — used by the composer at
    /// XhtmlComposer.java:318. For an element node `content` is always null.
    pub fn has_content(&self) -> bool {
        self.content.is_some()
    }

    pub fn add_child_node(&mut self, node: XhtmlNode) {
        self.child_nodes.push(node);
    }

    /// Java `addText` (XhtmlNode.java:303). Returns index of the new node so the
    /// parser can attach a location if needed (we don't track locations).
    pub fn add_text(&mut self, content: impl Into<String>) -> &mut XhtmlNode {
        let mut n = XhtmlNode::new(NodeType::Text);
        n.set_content(content.into());
        self.child_nodes.push(n);
        self.child_nodes.last_mut().unwrap()
    }

    /// Java `addComment` (XhtmlNode.java:267).
    pub fn add_comment(&mut self, content: impl Into<String>) -> &mut XhtmlNode {
        let mut n = XhtmlNode::new(NodeType::Comment);
        n.set_content(content.into());
        self.child_nodes.push(n);
        self.child_nodes.last_mut().unwrap()
    }

    /// Java `addCData` (XhtmlNode.java:276).
    pub fn add_cdata(&mut self, content: impl Into<String>) -> &mut XhtmlNode {
        let mut n = XhtmlNode::new(NodeType::CData);
        n.set_content(content.into());
        self.child_nodes.push(n);
        self.child_nodes.last_mut().unwrap()
    }

    /// Java `addDocType` (XhtmlNode.java:285).
    pub fn add_doc_type(&mut self, content: impl Into<String>) -> &mut XhtmlNode {
        let mut n = XhtmlNode::new(NodeType::DocType);
        n.set_content(content.into());
        self.child_nodes.push(n);
        self.child_nodes.last_mut().unwrap()
    }

    /// Java `addInstruction` (XhtmlNode.java:294).
    pub fn add_instruction(&mut self, content: impl Into<String>) -> &mut XhtmlNode {
        let mut n = XhtmlNode::new(NodeType::Instruction);
        n.set_content(content.into());
        self.child_nodes.push(n);
        self.child_nodes.last_mut().unwrap()
    }

    /// Java `makeTag` (XhtmlNode.java:218) as a free constructor: builds a
    /// detached element node with `notPretty` set for the inline set — the same
    /// state `add_tag` gives a child. Use this when building a node tree bottom
    /// up (fragment leaf renderers) rather than via a parent's `add_tag`.
    pub fn new_tag(name: impl Into<String>) -> XhtmlNode {
        let name = name.into();
        let mut node = XhtmlNode::new(NodeType::Element);
        if is_inline_no_pretty(&name) {
            node.not_pretty = true;
        }
        node.set_name(name);
        node
    }

    /// Java `addTag` -> `makeTag` (XhtmlNode.java:242, 218). `makeTag` also sets
    /// `notPretty` for the inline element set (XhtmlNode.java:236).
    pub fn add_tag(&mut self, name: impl Into<String>) -> &mut XhtmlNode {
        let name = name.into();
        let mut node = XhtmlNode::new(NodeType::Element);
        if is_inline_no_pretty(&name) {
            node.not_pretty = true;
        }
        node.set_name(name);
        self.child_nodes.push(node);
        self.child_nodes.last_mut().unwrap()
    }

    /// Java `allChildrenAreText` (XhtmlNode.java:353).
    pub fn all_children_are_text(&self) -> bool {
        // Java initializes res=true and only iterates if hasChildren(); an empty
        // node returns true.
        self.child_nodes
            .iter()
            .all(|n| n.node_type == NodeType::Text)
    }

    /// Java `allText` restricted to the composer's use: it is only called for
    /// `script`/`style` where `allChildrenAreText()` is true
    /// (XhtmlComposer.java:340-341). In that case all children are text nodes,
    /// so `allText` is just their concatenated content.
    pub fn all_text(&self) -> String {
        if self.child_nodes.is_empty() {
            return self.content.clone().unwrap_or_default();
        }
        let mut b = String::new();
        for n in &self.child_nodes {
            if n.node_type == NodeType::Text {
                if let Some(c) = &n.content {
                    b.push_str(c);
                }
            }
        }
        b
    }

    // --- emptyExpanded / notPretty ---

    /// Java `getEmptyExpanded` (XhtmlNode.java:563).
    pub fn empty_expanded(&self) -> Option<bool> {
        self.empty_expanded
    }

    /// Java `hasEmptyExpanded` (XhtmlNode.java:567).
    pub fn has_empty_expanded(&self) -> bool {
        self.empty_expanded.is_some()
    }

    /// Java `setEmptyExpanded` (XhtmlNode.java:571).
    pub fn set_empty_expanded(&mut self, v: bool) {
        self.empty_expanded = Some(v);
    }

    /// Java `isNoPretty` (XhtmlNode.java:752).
    pub fn is_no_pretty(&self) -> bool {
        self.not_pretty
    }

    /// Java `getNsDecl` (XhtmlNode.java:551).
    pub fn ns_decl(&self) -> Option<&str> {
        self.attributes.get("xmlns").and_then(|v| v.as_deref())
    }
}

/// The inline element set for which `makeTag` sets `notPretty`
/// (XhtmlNode.java:236). Note: includes a leading-space `" button"` typo
/// present verbatim in the Java source; reproduced for fidelity (it simply
/// never matches a real element name).
pub fn is_inline_no_pretty(name: &str) -> bool {
    matches!(
        name,
        "b" | "big"
            | "i"
            | "small"
            | "tt"
            | "abbr"
            | "acronym"
            | "cite"
            | "code"
            | "dfn"
            | "em"
            | "kbd"
            | "strong"
            | "samp"
            | "var"
            | "a"
            | "bdo"
            | "br"
            | "img"
            | "map"
            | "object"
            | "q"
            | "script"
            | "span"
            | "sub"
            | "sup"
            | " button"
            | "input"
            | "label"
            | "select"
            | "textarea"
            | "style"
    )
}
