//! Publisher `menu.xml` generated from prepared semantic navigation.

use site_build::MenuNode;

const HEADER: &str = "<!-- menu.xml {% comment %}\n\
*****************************************************************************************************\n\
*                                  WARNING: DO NOT EDIT THIS FILE                                   *\n\
*                                                                                                   *\n\
* This file is generated by SUSHI. Any edits you make to this file will be overwritten.             *\n\
*                                                                                                   *\n\
* To change the contents of this file, edit the \"menu\" attribute in the tank sushi-config.yaml file *\n\
* or provide your own menu.xml in the input/includes folder                                         *\n\
*****************************************************************************************************\n\
{% endcomment %} -->\n\n";

fn escape_xml(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Generate the stock Publisher/SUSHI navbar from prepared menu semantics.
/// Empty menus deliberately produce no include.
pub fn menu_xml(menu: &[MenuNode]) -> Option<String> {
    if menu.is_empty() {
        return None;
    }
    let mut out = String::from(HEADER);
    out.push_str("<ul xmlns=\"http://www.w3.org/1999/xhtml\" class=\"nav navbar-nav\">\n");
    for item in menu {
        if !item.items.is_empty() {
            out.push_str("  <li class=\"dropdown\">\n");
            out.push_str(&format!(
                "    <a data-toggle=\"dropdown\" href=\"#\" class=\"dropdown-toggle\">{}\n      <b class=\"caret\"></b>\n    </a>\n",
                escape_xml(&item.label)
            ));
            out.push_str("    <ul class=\"dropdown-menu\">\n");
            for child in &item.items {
                let Some(href) = child.href.as_deref() else {
                    continue;
                };
                out.push_str(&format!(
                    "      <li>\n        <a href=\"{}\">{}</a>\n      </li>\n",
                    escape_xml(href),
                    escape_xml(&child.label)
                ));
            }
            out.push_str("    </ul>\n  </li>\n");
        } else if let Some(href) = item.href.as_deref() {
            out.push_str(&format!(
                "  <li>\n    <a href=\"{}\">{}</a>\n  </li>\n",
                escape_xml(href),
                escape_xml(&item.label)
            ));
        }
    }
    out.push_str("</ul>");
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_order_and_matches_stock_markup() {
        let menu = vec![
            MenuNode {
                label: "Home & start".into(),
                href: Some("index.html?a=1&b=2".into()),
                items: Vec::new(),
            },
            MenuNode {
                label: "Guidance".into(),
                href: None,
                items: vec![
                    MenuNode {
                        label: "Overview".into(),
                        href: Some("guidance.html".into()),
                        items: Vec::new(),
                    },
                    MenuNode {
                        label: "Notes".into(),
                        href: Some("notes.html".into()),
                        items: Vec::new(),
                    },
                ],
            },
        ];
        let xml = menu_xml(&menu).unwrap();
        assert!(xml.contains("<a href=\"index.html?a=1&amp;b=2\">Home &amp; start</a>"));
        assert!(xml.find("Overview").unwrap() < xml.find("Notes").unwrap());
        assert!(xml.contains("class=\"dropdown-toggle\">Guidance"));
    }

    #[test]
    fn empty_menu_has_no_generated_include() {
        assert!(menu_xml(&[]).is_none());
    }
}
